export const SWAP_CURRENCY = "SWAP_CURRENCY";
export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const DEPARTURE_SELECTOR = "DEPARTURE_SELECTOR";
export const ARRIVAL_SELECTOR = "ARRIVAL_SELECTOR";
export const GET_RATES = "GET_RATES";
export const CHANGE_THEME = "CHANGE_THEME";
